# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0002_auto_20251203_0815'),
        ('usuarios', '0001_initial'),
        ('contratacion', '0002_auto_20251203_0815'),
        ('sitios', '0002_auto_20251203_0815'),
        ('facturacion', '0003_auto_20251203_0815'),
        ('clinico', '0003_auto_20251203_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSolicita', models.DateTimeField(blank=True, null=True)),
                ('fechaAtendio', models.DateTimeField(blank=True, null=True)),
                ('consec', models.IntegerField()),
                ('consecAdmision', models.IntegerField(default=0)),
                ('hClinica', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo', models.CharField(blank=True, max_length=1000, null=True)),
                ('examenFisico', models.CharField(blank=True, max_length=5000, null=True)),
                ('frecCardiaca', models.CharField(blank=True, max_length=10, null=True)),
                ('frecRespiratoria', models.CharField(blank=True, max_length=10, null=True)),
                ('taSist', models.CharField(blank=True, max_length=10, null=True)),
                ('taDiast', models.CharField(blank=True, max_length=10, null=True)),
                ('taMedia', models.CharField(blank=True, max_length=10, null=True)),
                ('glasgow', models.CharField(blank=True, max_length=10, null=True)),
                ('peso', models.CharField(blank=True, max_length=10, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=10, null=True)),
                ('estatura', models.CharField(blank=True, max_length=10, null=True)),
                ('glucometria', models.CharField(blank=True, max_length=50, null=True)),
                ('saturacion', models.CharField(blank=True, max_length=50, null=True)),
                ('escalaDolor', models.CharField(blank=True, max_length=50, null=True)),
                ('vistobno', models.CharField(blank=True, max_length=50, null=True)),
                ('tipoTrauma', models.CharField(blank=True, max_length=50, null=True)),
                ('cinematicaTrauma', models.CharField(blank=True, max_length=50, null=True)),
                ('tipoIngreso', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaModanexo', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(default='', max_length=5000)),
                ('alergiasTriage', models.CharField(default='', max_length=50)),
                ('salidaDefinitiva', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('causaExterna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.CausasExterna')),
                ('clasificacionTriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposTriage')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.Convenios')),
                ('dependencias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depCli01', to='sitios.Dependencias')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento1', to='usuarios.Usuarios')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Empresas')),
                ('enfermedaActual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Enfermedades')),
                ('regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Regimenes')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica1', to='sitios.SedesClinica')),
                ('serviciosAdministrativos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm02', to='sitios.ServiciosAdministrativos')),
                ('serviciosSedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Serv21', to='sitios.ServiciosSedes')),
                ('subServiciosSedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SubServ21', to='sitios.SubServiciosSedes')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento')),
                ('usuarioAtiende', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento2', to='planta.Planta')),
                ('usuarioAutoriza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
                ('usuarioCrea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento3', to='planta.Planta')),
                ('viaEgreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasEgreso')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='triage',
            unique_together={('tipoDoc', 'documento', 'consecAdmision')},
        ),
    ]
