xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\Administracion\admin.py" "C:\EntornosPython\pos7Particionado\vulner\Administracion\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\Administracion\forms.py" "C:\EntornosPython\pos7Particionado\vulner\Administracion\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\Administracion\models.py" "C:\EntornosPython\pos7Particionado\vulner\Administracion\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\Administracion\views.py" "C:\EntornosPython\pos7Particionado\vulner\Administracion\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\Administracion\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\Administracion\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\admisiones\admin.py" "C:\EntornosPython\pos7Particionado\vulner\admisiones\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\admisiones\forms.py" "C:\EntornosPython\pos7Particionado\vulner\admisiones\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\admisiones\models.py" "C:\EntornosPython\pos7Particionado\vulner\admisiones\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\admisiones\views.py" "C:\EntornosPython\pos7Particionado\vulner\admisiones\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\admisiones\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\admisiones\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\autorizaciones\admin.py" "C:\EntornosPython\pos7Particionado\vulner\autorizaciones\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\autorizaciones\forms.py" "C:\EntornosPython\pos7Particionado\vulner\autorizaciones\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\autorizaciones\models.py" "C:\EntornosPython\pos7Particionado\vulner\autorizaciones\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\autorizaciones\views.py" "C:\EntornosPython\pos7Particionado\vulner\autorizaciones\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\autorizaciones\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\autorizaciones\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\basicas\admin.py" "C:\EntornosPython\pos7Particionado\vulner\basicas\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\basicas\forms.py" "C:\EntornosPython\pos7Particionado\vulner\basicas\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\basicas\models.py" "C:\EntornosPython\pos7Particionado\vulner\basicas\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\basicas\views.py" "C:\EntornosPython\pos7Particionado\vulner\basicas\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\basicas\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\basicas\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\camara\admin.py" "C:\EntornosPython\pos7Particionado\vulner\camara\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\camara\forms.py" "C:\EntornosPython\pos7Particionado\vulner\camara\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\camara\models.py" "C:\EntornosPython\pos7Particionado\vulner\camara\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\camara\views.py" "C:\EntornosPython\pos7Particionado\vulner\camara\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\camara\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\camara\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\cartera\admin.py" "C:\EntornosPython\pos7Particionado\vulner\cartera\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\cartera\forms.py" "C:\EntornosPython\pos7Particionado\vulner\cartera\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\cartera\models.py" "C:\EntornosPython\pos7Particionado\vulner\cartera\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\cartera\views.py" "C:\EntornosPython\pos7Particionado\vulner\cartera\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\cartera\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\cartera\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\cirugia\admin.py" "C:\EntornosPython\pos7Particionado\vulner\cirugia\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\cirugia\forms.py" "C:\EntornosPython\pos7Particionado\vulner\cirugia\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\cirugia\models.py" "C:\EntornosPython\pos7Particionado\vulner\cirugia\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\cirugia\views.py" "C:\EntornosPython\pos7Particionado\vulner\cirugia\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\cirugia\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\cirugia\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\citasMedicas\admin.py" "C:\EntornosPython\pos7Particionado\vulner\citasMedicas\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\citasMedicas\forms.py" "C:\EntornosPython\pos7Particionado\vulner\citasMedicas\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\citasMedicas\models.py" "C:\EntornosPython\pos7Particionado\vulner\citasMedicas\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\citasMedicas\views.py" "C:\EntornosPython\pos7Particionado\vulner\citasMedicas\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\citasMedicas\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\citasMedicas\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\clinico\admin.py" "C:\EntornosPython\pos7Particionado\vulner\clinico\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\clinico\forms.py" "C:\EntornosPython\pos7Particionado\vulner\clinico\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\clinico\models.py" "C:\EntornosPython\pos7Particionado\vulner\clinico\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\clinico\views.py" "C:\EntornosPython\pos7Particionado\vulner\clinico\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\clinico\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\clinico\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\contratacion\admin.py" "C:\EntornosPython\pos7Particionado\vulner\contratacion\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\contratacion\forms.py" "C:\EntornosPython\pos7Particionado\vulner\contratacion\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\contratacion\models.py" "C:\EntornosPython\pos7Particionado\vulner\contratacion\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\contratacion\views.py" "C:\EntornosPython\pos7Particionado\vulner\contratacion\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\contratacion\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\contratacion\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\enfermeria\admin.py" "C:\EntornosPython\pos7Particionado\vulner\enfermeria\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\enfermeria\forms.py" "C:\EntornosPython\pos7Particionado\vulner\enfermeria\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\enfermeria\models.py" "C:\EntornosPython\pos7Particionado\vulner\enfermeria\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\enfermeria\views.py" "C:\EntornosPython\pos7Particionado\vulner\enfermeria\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\enfermeria\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\enfermeria\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\facturacion\admin.py" "C:\EntornosPython\pos7Particionado\vulner\facturacion\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\facturacion\forms.py" "C:\EntornosPython\pos7Particionado\vulner\facturacion\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\facturacion\models.py" "C:\EntornosPython\pos7Particionado\vulner\facturacion\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\facturacion\views.py" "C:\EntornosPython\pos7Particionado\vulner\facturacion\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\facturacion\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\facturacion\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\farmacia\admin.py" "C:\EntornosPython\pos7Particionado\vulner\farmacia\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\farmacia\forms.py" "C:\EntornosPython\pos7Particionado\vulner\farmacia\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\farmacia\models.py" "C:\EntornosPython\pos7Particionado\vulner\farmacia\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\farmacia\views.py" "C:\EntornosPython\pos7Particionado\vulner\farmacia\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\farmacia\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\farmacia\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\inventarios\admin.py" "C:\EntornosPython\pos7Particionado\vulner\inventarios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\inventarios\forms.py" "C:\EntornosPython\pos7Particionado\vulner\inventarios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\inventarios\models.py" "C:\EntornosPython\pos7Particionado\vulner\inventarios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\inventarios\views.py" "C:\EntornosPython\pos7Particionado\vulner\inventarios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\inventarios\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\inventarios\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\mecanicoPacientes\admin.py" "C:\EntornosPython\pos7Particionado\vulner\mecanicoPacientes\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\mecanicoPacientes\forms.py" "C:\EntornosPython\pos7Particionado\vulner\mecanicoPacientes\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\mecanicoPacientes\models.py" "C:\EntornosPython\pos7Particionado\vulner\mecanicoPacientes\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\mecanicoPacientes\views.py" "C:\EntornosPython\pos7Particionado\vulner\mecanicoPacientes\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\mecanicoPacientes\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\mecanicoPacientes\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\planta\admin.py" "C:\EntornosPython\pos7Particionado\vulner\planta\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\planta\forms.py" "C:\EntornosPython\pos7Particionado\vulner\planta\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\planta\models.py" "C:\EntornosPython\pos7Particionado\vulner\planta\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\planta\views.py" "C:\EntornosPython\pos7Particionado\vulner\planta\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\planta\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\planta\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\referencia\admin.py" "C:\EntornosPython\pos7Particionado\vulner\referencia\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\referencia\forms.py" "C:\EntornosPython\pos7Particionado\vulner\referencia\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\referencia\models.py" "C:\EntornosPython\pos7Particionado\vulner\referencia\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\referencia\views.py" "C:\EntornosPython\pos7Particionado\vulner\referencia\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\referencia\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\referencia\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\Reportes\admin.py" "C:\EntornosPython\pos7Particionado\vulner\Reportes\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\Reportes\forms.py" "C:\EntornosPython\pos7Particionado\vulner\Reportes\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\Reportes\models.py" "C:\EntornosPython\pos7Particionado\vulner\Reportes\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\Reportes\views.py" "C:\EntornosPython\pos7Particionado\vulner\Reportes\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\Reportes\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\Reportes\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\rips\admin.py" "C:\EntornosPython\pos7Particionado\vulner\rips\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\rips\forms.py" "C:\EntornosPython\pos7Particionado\vulner\rips\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\rips\models.py" "C:\EntornosPython\pos7Particionado\vulner\rips\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\rips\views.py" "C:\EntornosPython\pos7Particionado\vulner\rips\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\rips\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\rips\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\seguridad\admin.py" "C:\EntornosPython\pos7Particionado\vulner\seguridad\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\seguridad\forms.py" "C:\EntornosPython\pos7Particionado\vulner\seguridad\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\seguridad\models.py" "C:\EntornosPython\pos7Particionado\vulner\seguridad\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\seguridad\views.py" "C:\EntornosPython\pos7Particionado\vulner\seguridad\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\seguridad\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\seguridad\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\sitios\admin.py" "C:\EntornosPython\pos7Particionado\vulner\sitios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\sitios\forms.py" "C:\EntornosPython\pos7Particionado\vulner\sitios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\sitios\models.py" "C:\EntornosPython\pos7Particionado\vulner\sitios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\sitios\views.py" "C:\EntornosPython\pos7Particionado\vulner\sitios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\sitios\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\sitios\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\tarifarios\admin.py" "C:\EntornosPython\pos7Particionado\vulner\tarifarios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\tarifarios\forms.py" "C:\EntornosPython\pos7Particionado\vulner\tarifarios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\tarifarios\models.py" "C:\EntornosPython\pos7Particionado\vulner\tarifarios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\tarifarios\views.py" "C:\EntornosPython\pos7Particionado\vulner\tarifarios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\tarifarios\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\tarifarios\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\terapeutico\admin.py" "C:\EntornosPython\pos7Particionado\vulner\terapeutico\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\terapeutico\forms.py" "C:\EntornosPython\pos7Particionado\vulner\terapeutico\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\terapeutico\models.py" "C:\EntornosPython\pos7Particionado\vulner\terapeutico\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\terapeutico\views.py" "C:\EntornosPython\pos7Particionado\vulner\terapeutico\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\terapeutico\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\terapeutico\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\triage\admin.py" "C:\EntornosPython\pos7Particionado\vulner\triage\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\triage\forms.py" "C:\EntornosPython\pos7Particionado\vulner\triage\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\triage\models.py" "C:\EntornosPython\pos7Particionado\vulner\triage\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\triage\views.py" "C:\EntornosPython\pos7Particionado\vulner\triage\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\triage\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\triage\"

xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\usuarios\admin.py" "C:\EntornosPython\pos7Particionado\vulner\usuarios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\usuarios\forms.py" "C:\EntornosPython\pos7Particionado\vulner\usuarios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\usuarios\models.py" "C:\EntornosPython\pos7Particionado\vulner\usuarios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\usuarios\views.py" "C:\EntornosPython\pos7Particionado\vulner\usuarios\"
xcopy /s/e/y "C:\EntornosPython\pos7ParticionadoLienzo\vulner\usuarios\viewsReportes.py" "C:\EntornosPython\pos7Particionado\vulner\usuarios\"

REM SOLO FALTA DE VULNER
REL urls.py y settings.py