# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('sitios', '0001_initial'),
        ('facturacion', '0002_auto_20251203_0815'),
        ('rips', '0001_initial'),
        ('clinico', '0002_auto_20251203_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estancias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=5, null=True)),
                ('codigo', models.CharField(blank=True, max_length=6, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
                ('tipoEstancia', models.CharField(choices=[('S', 'SOAT'), ('I', 'ISS'), ('P', 'PARTICULAR')], default='I', editable=False, max_length=1)),
                ('valor', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('cups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cupsEstancias01', to='clinico.Examenes')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='GruposQx',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MinimosLegales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('año', models.CharField(blank=True, max_length=4, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TablaHonorariosIss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homologado', models.CharField(blank=True, max_length=8, null=True)),
                ('valorUvr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TablaHonorariosSoat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homologado', models.CharField(blank=True, max_length=8, null=True)),
                ('smldv', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('grupoQx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.GruposQx')),
            ],
        ),
        migrations.CreateModel(
            name='TablaMaterialSuturaCuracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homologado', models.CharField(blank=True, max_length=8, null=True)),
                ('smldv', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cruento', models.CharField(blank=True, editable=False, max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('grupoQx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.GruposQx')),
                ('minimosLegales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.MinimosLegales')),
            ],
        ),
        migrations.CreateModel(
            name='TablaMaterialSuturaCuracionIss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homologado', models.CharField(blank=True, max_length=8, null=True)),
                ('desdeUvr', models.CharField(blank=True, max_length=3, null=True)),
                ('hastaUvr', models.CharField(blank=True, max_length=3, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TablaSalasDeCirugia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homologado', models.CharField(blank=True, max_length=8, null=True)),
                ('smldv', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cruento', models.CharField(blank=True, editable=False, max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('grupoQx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.GruposQx')),
            ],
        ),
        migrations.CreateModel(
            name='TablaSalasDeCirugiaIss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homologado', models.CharField(blank=True, max_length=8, null=True)),
                ('desdeUvr', models.CharField(blank=True, max_length=3, null=True)),
                ('hastaUvr', models.CharField(blank=True, max_length=3, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TarifariosDescripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('columna', models.CharField(blank=True, max_length=15, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('serviciosAdministrativos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm30', to='sitios.ServiciosAdministrativos')),
            ],
        ),
        migrations.CreateModel(
            name='TarifariosDescripcionHonorarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TarifariosProcedimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('colValorBase', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor1', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor2', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor3', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor4', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor5', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor6', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor7', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor8', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor9', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor10', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('codigoCups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups10121', to='clinico.Examenes')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto2271', to='facturacion.Conceptos')),
                ('serviciosAdministrativos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm31', to='sitios.ServiciosAdministrativos')),
            ],
        ),
        migrations.CreateModel(
            name='TarifariosProcedimientosHonorarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('valorHonorarioCirujano', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('valorHonorarioAnestesiologo', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('valorHonorarioAyudante', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('valorHonorarioPerfucionista', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('valorHonorarioViaAcceso', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('valorHonorarioUnicaVia', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('valorHonorarioDobleVia', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('codigoCups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups101211', to='clinico.Examenes')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto22714', to='facturacion.Conceptos')),
                ('serviciosAdministrativos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm33', to='sitios.ServiciosAdministrativos')),
            ],
        ),
        migrations.CreateModel(
            name='TarifariosSuministros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('colValorBase', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor1', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor2', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor3', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor4', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor5', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor6', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor7', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor8', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor9', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('colValor10', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('codigoCum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suministro10121', to='facturacion.Suministros')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto22712', to='facturacion.Conceptos')),
                ('serviciosAdministrativos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm34', to='sitios.ServiciosAdministrativos')),
            ],
        ),
        migrations.CreateModel(
            name='TiposHonorarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('ripsTipoOtrosServicios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipooTROsERV01', to='rips.RipsTipoOtrosServicios')),
            ],
        ),
        migrations.CreateModel(
            name='TiposTarifa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposTarifaProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='tipostarifa',
            name='tiposTarifaProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa11', to='tarifarios.TiposTarifaProducto'),
        ),
        migrations.AddField(
            model_name='tarifariossuministros',
            name='tiposTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa172', to='tarifarios.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='tarifariossuministros',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas20202', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='tarifariosprocedimientoshonorarios',
            name='tiposTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa1711', to='tarifarios.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='tarifariosprocedimientoshonorarios',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas20205', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='tarifariosprocedimientos',
            name='tiposTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa171', to='tarifarios.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='tarifariosprocedimientos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas2020', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='tarifariosdescripcion',
            name='tiposTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa11', to='tarifarios.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='tablasalasdecirugiaiss',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario11222', to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='tablasalasdecirugiaiss',
            name='tiposSala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.TiposSalas'),
        ),
        migrations.AddField(
            model_name='tablasalasdecirugiaiss',
            name='tiposTarifaProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposTarifaProducto'),
        ),
        migrations.AddField(
            model_name='tablasalasdecirugiaiss',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='tablasalasdecirugia',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario14452', to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='tablasalasdecirugia',
            name='tiposTarifaProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposTarifaProducto'),
        ),
        migrations.AddField(
            model_name='tablasalasdecirugia',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='tablamaterialsuturacuracioniss',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario11244', to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='tablamaterialsuturacuracioniss',
            name='tiposSala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.TiposSalas'),
        ),
        migrations.AddField(
            model_name='tablamaterialsuturacuracioniss',
            name='tiposTarifaProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposTarifaProducto'),
        ),
        migrations.AddField(
            model_name='tablamaterialsuturacuracioniss',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='tablamaterialsuturacuracion',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario14754', to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='tablamaterialsuturacuracion',
            name='tiposTarifaProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposTarifaProducto'),
        ),
        migrations.AddField(
            model_name='tablamaterialsuturacuracion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='tablahonorariossoat',
            name='tiposHonorarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='tablahonorariossoat',
            name='tiposTarifaProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposTarifaProducto'),
        ),
        migrations.AddField(
            model_name='tablahonorariossoat',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='tablahonorariosiss',
            name='tiposHonorarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='tablahonorariosiss',
            name='tiposTarifaProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposTarifaProducto'),
        ),
        migrations.AddField(
            model_name='tablahonorariosiss',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddIndex(
            model_name='tarifariossuministros',
            index=models.Index(fields=['tiposTarifa', 'codigoCum'], name='tarifSuministTipostarifaIdx'),
        ),
        migrations.AddIndex(
            model_name='tarifariosprocedimientos',
            index=models.Index(fields=['tiposTarifa', 'codigoCups'], name='tarifProcedTipostarifaIdx'),
        ),
    ]
