# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartera', '0002_auto_20251203_0815'),
        ('planta', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('contratacion', '0002_auto_20251203_0815'),
        ('sitios', '0001_initial'),
        ('clinico', '0003_auto_20251203_0815'),
        ('facturacion', '0002_auto_20251203_0815'),
        ('cirugia', '0003_auto_20251203_0815'),
        ('rips', '0001_initial'),
        ('tarifarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministros',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='tipoSuministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposSuministro'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='unidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsUmm'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='viaAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasAdministracion'),
        ),
        migrations.AddField(
            model_name='regimenestipopago',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Regimenes'),
        ),
        migrations.AddField(
            model_name='regimenestipopago',
            name='salarioLegal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.SalariosLegales'),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoFac4', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica667', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm51', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TiposDoc145', to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta123', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ciru0111', to='cirugia.Cirugias'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Conceptos0005', to='facturacion.Conceptos'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='cums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suministros05', to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups101', to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='historiaMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histmed02', to='clinico.HistoriaMedicamentos'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Liquid01', to='facturacion.Liquidacion'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario091', to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='usuarioModifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planat121', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta122', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='liquidacioncirugias',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='liquidacioncirugias',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Convenio102', to='contratacion.Convenios'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoFac3', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica789', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm21', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TiposDoc120', to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='usuarioAnula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta108', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta109', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ciru01112', to='cirugia.Cirugias'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Conceptos1115', to='facturacion.Conceptos'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='cums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Sum102', to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups121', to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='facturacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Fact01', to='facturacion.Facturacion'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='glosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups129', to='cartera.Glosas'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='historiaMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histmed01', to='clinico.HistoriaMedicamentos'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups121', to='cartera.NotasCredito'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='notaDebito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups121', to='cartera.NotasDebito'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos108', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario099', to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='usuarioCrea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta105', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='usuarioModifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta106', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta107', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Conv08', to='contratacion.Convenios'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoFac2', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='ripsEnvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsEnvios'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica398', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm20', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TiposDoc101', to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='usuarioAnula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Plantas100', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Plantas101', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Depto01', to='sitios.Departamentos'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Muni01', to='sitios.Municipios'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Regimenes'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tipoEmpresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposEmpresa'),
        ),
        migrations.AddField(
            model_name='eapb',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenios0221', to='contratacion.Convenios'),
        ),
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria2', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Facturacion'),
        ),
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='conceptosafacturar',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='conceptos',
            name='tipoCups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='conceptos',
            name='tiposSuministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposSuministro'),
        ),
        migrations.AddIndex(
            model_name='suministros',
            index=models.Index(fields=['nombre'], name='suministrosNombreIdx'),
        ),
        migrations.AlterUniqueTogether(
            name='conveniospacienteingresos',
            unique_together={('tipoDoc', 'documento', 'consecAdmision', 'convenio')},
        ),
    ]
