# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('contratacion', '0001_initial'),
        ('sitios', '0001_initial'),
        ('facturacion', '0002_auto_20251203_0815'),
        ('rips', '0001_initial'),
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisiones',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica763', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='remisiones',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='radicaciones',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica762', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='radicaciones',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm08', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='radicaciones',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='pagosfacturas',
            name='facturaAplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Facturacion'),
        ),
        migrations.AddField(
            model_name='pagosfacturas',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.Pagos'),
        ),
        migrations.AddField(
            model_name='pagosfacturas',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica7647', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='pagosfacturas',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm06', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.Caja'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.Convenios'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento77', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='formaPago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.FormasPagos'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica7645', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm05', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='tipoPago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.TiposPagos'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Empresas'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturacion07', to='facturacion.Facturacion'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos12', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica760', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm12', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario797', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='notaCreditoDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.NotasCreditoDetalle'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='ripsConsultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsCons0xy1', to='rips.RipsConsultas'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='ripsMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsMedic0xy1', to='rips.RipsMedicamentos'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='ripsOtrosServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsOtros0xy2', to='rips.RipsOtrosServicios'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='ripsProcedimientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsProced0xy1', to='rips.RipsProcedimientos'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='tiposNotasCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposNotaCre02', to='cartera.TiposNotasCredito'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7956', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturacion103', to='facturacion.Facturacion'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.NotasCredito'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='tiposNotasCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposNotaCre01', to='cartera.TiposNotasCredito'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario796', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsDetalle'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='ripsEnvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsEnvios'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos11', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica765', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm11', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario799', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='motivosglosas',
            name='conceptoEspecifico',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.GlosasConceptoEspecifico'),
        ),
        migrations.AddField(
            model_name='motivosglosas',
            name='conceptoGeneral',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.GlosasConceptoGeneral'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='glosasDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.GlosasDetalle'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='motivoGlosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.MotivosGlosas'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsConsultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsCons01', to='rips.RipsConsultas'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsMedic01', to='rips.RipsMedicamentos'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsOtrosServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsOtros01', to='rips.RipsOtrosServicios'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsProcedimientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsProced01', to='rips.RipsProcedimientos'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos10', to='rips.RipsTipos'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario79533', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturacion10322', to='facturacion.Facturacion'),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='glosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.Glosas'),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7423', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='glosasconceptoespecifico',
            name='conceptoGeneral',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.GlosasConceptoGeneral'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='estadoRadicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoGloas02', to='cartera.EstadosGlosas'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='estadoRecepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoGlosa01', to='cartera.EstadosGlosas'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='ripsEnvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsEnvios'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica764', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm10', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='tipoGlosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoGlosa01', to='cartera.TiposGlosas'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='usuarioRecepcion',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepcion01', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario987', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='usuarioRespuesta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuesta01', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='caja',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica7648', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='caja',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm335', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuarioEntrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7397', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuarioRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7597', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7297', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuarioSuperviza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7497', to='planta.Planta'),
        ),
    ]
