# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('enfermeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnosenfermeria',
            name='enfermeraTurno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
    ]
