# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('farmacia', '0002_auto_20251203_0815'),
        ('usuarios', '0001_initial'),
        ('sitios', '0001_initial'),
        ('clinico', '0003_auto_20251203_0815'),
        ('facturacion', '0002_auto_20251203_0815'),
        ('cirugia', '0003_auto_20251203_0815'),
        ('enfermeria', '0002_turnosenfermeria_enfermeraturno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnosenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica_398', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='turnosenfermeria',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serenf01', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='turnosenfermeria',
            name='tiposTurnosEnfermeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposTurno01', to='enfermeria.TiposTurnosEnfermeria'),
        ),
        migrations.AddField(
            model_name='turnosenfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioenf02', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='tiposturnosenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica_377', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='tiposturnosenfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioenf01', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='signosenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaSignosEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='signosenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica385', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='signosenfermeria',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.TurnosEnfermeria'),
        ),
        migrations.AddField(
            model_name='signosenfermeria',
            name='usuCompVascular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usu15', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='signosenfermeria',
            name='usuCompresp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usu13', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='signosenfermeria',
            name='usuGastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usu14', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='signosenfermeria',
            name='usuSignosNeurologicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usu12', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='signosenfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='posicionpacientesenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaPosicionEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='posicionpacientesenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica381', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='posicionpacientesenfermeria',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.TurnosEnfermeria'),
        ),
        migrations.AddField(
            model_name='posicionpacientesenfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='notasenfermeria',
            name='acompañante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.UsuariosContacto'),
        ),
        migrations.AddField(
            model_name='notasenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaNotasEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='notasenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica383', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='notasenfermeria',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.TurnosEnfermeria'),
        ),
        migrations.AddField(
            model_name='notasenfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='heridasenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaHeridasEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='heridasenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica380', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='heridasenfermeria',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.TurnosEnfermeria'),
        ),
        migrations.AddField(
            model_name='heridasenfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriatipoorigen',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3467', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriatipomovimiento',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3469', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='despachos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDispensa01', to='farmacia.FarmaciaDespachos'),
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='dosisUnidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.UnidadesDeMedidaDosis'),
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='enfermeriaDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EnfermeriaDetalle1101', to='enfermeria.EnfermeriaDetalle'),
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='farmaciaDespachosDispensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmaciaDespachosDispensa0222', to='farmacia.FarmaciaDespachosDispensa'),
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='farmaciaDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmaciaDetalle02', to='farmacia.FarmaciaDetalle'),
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3478', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriarecibe',
            name='viaAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasAdministracion'),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='dosisUnidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.UnidadesDeMedidaDosis'),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='enfermeraAplica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaEnfermera3468', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='enfermeraPlanea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaEnfermeraPlanea3468', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='enfermeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.Enfermeria'),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='enfermeriaRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EnfermeriaRecibe1102', to='enfermeria.EnfermeriaRecibe'),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='frecuencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.FrecuenciasAplicacion'),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='turnoEnfermeriaAplica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EnfermeriaTipoTurno11013', to='enfermeria.TurnosEnfermeria'),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='turnoEnfermeriaPlanea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EnfermeriaTipoTurno11012', to='enfermeria.TurnosEnfermeria'),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3488', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriaplaneacion',
            name='viaAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasAdministracion'),
        ),
        migrations.AddField(
            model_name='enfermeriadevoluciondetalle',
            name='enfermeriaDevolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EnfermeriDevolos261201', to='enfermeria.EnfermeriaDevolucion'),
        ),
        migrations.AddField(
            model_name='enfermeriadevoluciondetalle',
            name='enfermeriaRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EnfermeriaRecibe201', to='enfermeria.EnfermeriaRecibe'),
        ),
        migrations.AddField(
            model_name='enfermeriadevoluciondetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaEnfermeria3453', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica3Enf9022', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='serviciosAdministrativosDevuelve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servDevuelve3231', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='serviciosAdministrativosRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servRecibe32431', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='usuarioDevuelve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaDevuelve4353', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='usuarioRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaRecibe4553', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriadevolucion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaEnfermeriaia3453', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriadetalle',
            name='dosisUnidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.UnidadesDeMedidaDosis'),
        ),
        migrations.AddField(
            model_name='enfermeriadetalle',
            name='enfermeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Enfermeria01', to='enfermeria.Enfermeria'),
        ),
        migrations.AddField(
            model_name='enfermeriadetalle',
            name='farmaciaDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmaciaDetalle', to='farmacia.FarmaciaDetalle'),
        ),
        migrations.AddField(
            model_name='enfermeriadetalle',
            name='frecuencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.FrecuenciasAplicacion'),
        ),
        migrations.AddField(
            model_name='enfermeriadetalle',
            name='historiaMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmEnfermeria102', to='clinico.HistoriaMedicamentos'),
        ),
        migrations.AddField(
            model_name='enfermeriadetalle',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='enfermeriadetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3462', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='enfermeriadetalle',
            name='viaAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasAdministracion'),
        ),
        migrations.AddField(
            model_name='enfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='enfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica386', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='enfermeria',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmEnfermeria101', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='enfermeria',
            name='tipoMovimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoEnfermeria02', to='enfermeria.EnfermeriaTipoMovimiento'),
        ),
        migrations.AddField(
            model_name='enfermeria',
            name='tipoOrigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoEnfermeria01', to='enfermeria.EnfermeriaTipoOrigen'),
        ),
        migrations.AddField(
            model_name='enfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3460', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='dolorenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaDolorEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='dolorenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica379', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='dolorenfermeria',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.TurnosEnfermeria'),
        ),
        migrations.AddField(
            model_name='dolorenfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='cuidadosenfermeria',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.Cirugias'),
        ),
        migrations.AddField(
            model_name='cuidadosenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaCuidadosEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='cuidadosenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica378', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='cuidadosenfermeria',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.TurnosEnfermeria'),
        ),
        migrations.AddField(
            model_name='cuidadosenfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioenf03', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='adminMañana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin001', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='adminNoche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin003', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='adminTarfe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin002', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaBalanceLiquidosEnfermeria01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica384', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.TipoBalanceLiquidosEnfermeria'),
        ),
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enfermeria.TurnosEnfermeria'),
        ),
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
    ]
