# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('admisiones', '0002_auto_20251203_0815'),
        ('usuarios', '0001_initial'),
        ('basicas', '0002_eventos_causasexterna'),
        ('sitios', '0001_initial'),
        ('facturacion', '0002_auto_20251203_0815'),
        ('rips', '0001_initial'),
        ('clinico', '0002_auto_20251203_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='contactoAcompañante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contac01', to='usuarios.UsuariosContacto'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='contactoResponsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contac02', to='usuarios.UsuariosContacto'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dependenciasActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id1', to='sitios.Dependencias'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dependenciasIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id0', to='sitios.Dependencias'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dependenciasSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id2', to='sitios.Dependencias'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id4', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxComplicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id75', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id3', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id5', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Empresas'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='especialidadesMedicosActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspAct', to='clinico.EspecialidadesMedicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='especialidadesMedicosIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspIng', to='clinico.EspecialidadesMedicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='especialidadesMedicosSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspSal', to='clinico.EspecialidadesMedicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='estadoSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.EstadosSalida'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ipsRemite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Ips'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id7', to='clinico.Medicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoDefuncion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Medicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id6', to='clinico.Medicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id8', to='clinico.Medicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Regimenes'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsCausaMotivoAtencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsCausaExterna'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsCodServicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsServicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsCondicionDestinoUsuarioEgreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios10', to='rips.RipsDestinoEgreso'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsDestinoUsuarioEgresoRecienNacido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssDestino12', to='rips.RipsDestinoEgreso'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsFinalidadConsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsFinalidadConsulta'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsGrupoServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsGrupoServicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsServiciosActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios02', to='rips.RipsServicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsServiciosIng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios01', to='rips.RipsServicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsServiciosSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios03', to='rips.RipsServicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsTipoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsTipousuario12', to='rips.RipsTipoUsuario'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsViaIngresoServicioSalud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsViasIngresoSalud'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsmodalidadGrupoServicioTecSal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsModalidadAtencion'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='salidaMotivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidaMotivo01', to='clinico.TiposSalidas'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='serviciosActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id10', to='sitios.ServiciosSedes'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm01', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='serviciosIng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id9', to='sitios.ServiciosSedes'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='serviciosSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id11', to='sitios.ServiciosSedes'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='tiposCotizante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposCotizante'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='furips',
            name='departamentoEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dept10', to='sitios.Departamentos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='departamentoInvolucrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dept12', to='sitios.Departamentos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='departamentoPropietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dept11', to='sitios.Departamentos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documentofur', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='furips',
            name='documentoProfesionalAtendio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='furips',
            name='documentoVictima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento14', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='furips',
            name='dxPrincEgreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx4', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='dxPrincIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx1', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='dxRel1Egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx5', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='dxRel1Ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx2', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='dxRel2Egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx6', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='dxRel2Ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx3', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicas.Eventos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='localidadEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local09', to='sitios.Localidades'),
        ),
        migrations.AddField(
            model_name='furips',
            name='localidadInvolucrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Localidades'),
        ),
        migrations.AddField(
            model_name='furips',
            name='localidadPropietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local10', to='sitios.Localidades'),
        ),
        migrations.AddField(
            model_name='furips',
            name='municipioEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muni10', to='sitios.Municipios'),
        ),
        migrations.AddField(
            model_name='furips',
            name='municipioInvolucrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muni12', to='sitios.Municipios'),
        ),
        migrations.AddField(
            model_name='furips',
            name='municipioPropietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muni11', to='sitios.Municipios'),
        ),
        migrations.AddField(
            model_name='furips',
            name='prestadorRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ips86', to='clinico.Ips'),
        ),
        migrations.AddField(
            model_name='furips',
            name='prestadorRemite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ips7', to='clinico.Ips'),
        ),
        migrations.AddField(
            model_name='furips',
            name='profesionalRemite',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta112', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='furips',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica3', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='furips',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='furips',
            name='tipoDocInvolucrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoDoc15', to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='furips',
            name='tipoDocProfesionalAtendio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoDoc16', to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='furips',
            name='tipoDocPropietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoDoc17', to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='furips',
            name='tipoDocVictima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoDoc14', to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='furips',
            name='usuarioCrea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta111', to='planta.Planta'),
        ),
        migrations.AlterUniqueTogether(
            name='ingresos',
            unique_together={('tipoDoc', 'documento', 'consec', 'fechaIngreso')},
        ),
    ]
