# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RipsCausaExterna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsConceptoRecaudo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsConsultas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codPrestador', models.CharField(blank=True, max_length=12, null=True)),
                ('fechaInicioAtencion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('numAutorizacion', models.CharField(blank=True, max_length=30, null=True)),
                ('tipoDiagnosticoPrincipal', models.CharField(choices=[('UNO', 'Impresion Diagnostica'), ('DOS', 'Confirmado nuevo'), ('TRES', 'Confirmado repetido')], default='A', editable=False, max_length=21)),
                ('numDocumentoIdentificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('vrServicio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorPagoModerador', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('numFEVPagoModerador', models.CharField(blank=True, max_length=20, null=True)),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
                ('itemFactura', models.IntegerField(blank=True, null=True)),
                ('notasCreditoGlosa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notasCreditoOtras', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notasDebito', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RipsCums',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cum', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('codigoAtc', models.CharField(blank=True, max_length=50, null=True)),
                ('nombreAtc', models.CharField(blank=True, max_length=300, null=True)),
                ('invima', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsCups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RipsDci',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsDestinoEgreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuv', models.CharField(blank=True, max_length=500, null=True)),
                ('estadoPasoMinisterio', models.CharField(choices=[('E', 'Enviada'), ('R', 'Rechazada'), ('S', 'SinRespuesta')], default='E', editable=False, max_length=10)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('rutaJsonFactura', models.CharField(blank=True, max_length=5000, null=True)),
                ('rutaJsonRespuesta', models.CharField(blank=True, max_length=5000, null=True)),
                ('rutaZip', models.CharField(blank=True, max_length=5000, null=True)),
                ('rutaPdf', models.CharField(blank=True, max_length=5000, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RipsEnvios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fechaEnvio', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fechaRadicacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fechaGeneracionjson', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fechaRespuesta', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('respuesta', models.CharField(blank=True, max_length=50000, null=True)),
                ('rutaRespuestaJson', models.CharField(blank=True, max_length=5000, null=True)),
                ('cantidadFacturas', models.CharField(blank=True, max_length=5, null=True)),
                ('cantidadPasaron', models.CharField(blank=True, max_length=5, null=True)),
                ('cantidadRechazadas', models.CharField(blank=True, max_length=5, null=True)),
                ('rutaJson', models.CharField(blank=True, max_length=5000, null=True)),
                ('rutaZip', models.CharField(blank=True, max_length=5000, null=True)),
                ('rutaPdf', models.CharField(blank=True, max_length=5000, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RipsEstados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsFinalidadConsulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsFormaFarmaceutica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=6, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsGrupoServicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsHospitalizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codPrestador', models.CharField(blank=True, max_length=12, null=True)),
                ('fechaInicioAtencion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('numAutorizacion', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaEgreso', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RipsMedicamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codPrestador', models.CharField(blank=True, max_length=12, null=True)),
                ('numAutorizacion', models.CharField(blank=True, max_length=30, null=True)),
                ('idMIPRES', models.CharField(blank=True, max_length=15, null=True)),
                ('fechaDispensAdmon', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('nomTecnologiaSalud', models.CharField(blank=True, max_length=30, null=True)),
                ('concentracionMedicamento', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidadMedicamento', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('diasTratamiento', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('numDocumentoIdentificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('vrUnitMedicamento', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('vrServicio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valorPagoModerador', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('numFEVPagoModerador', models.CharField(blank=True, max_length=20, null=True)),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
                ('itemFactura', models.IntegerField(blank=True, null=True)),
                ('notasCreditoGlosa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notasCreditoOtras', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notasDebito', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RipsModalidadAtencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsMunicipios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsOtrosServicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codPrestador', models.CharField(blank=True, max_length=12, null=True)),
                ('numAutorizacion', models.CharField(blank=True, max_length=30, null=True)),
                ('idMIPRES', models.CharField(blank=True, max_length=15, null=True)),
                ('fechaSuministroTecnologia', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('nomTecnologiaSalud', models.CharField(blank=True, max_length=60, null=True)),
                ('nomTecnologiaSaludCups', models.CharField(blank=True, max_length=60, null=True)),
                ('cantidadOS', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('numDocumentoIdentificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('vrUnitOS', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('vrServicio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valorPagoModerador', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('numFEVPagoModerador', models.CharField(blank=True, max_length=20, null=True)),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
                ('itemFactura', models.IntegerField(blank=True, null=True)),
                ('notasCreditoGlosa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notasCreditoOtras', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notasDebito', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RipsPaises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsProcedimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codPrestador', models.CharField(blank=True, max_length=12, null=True)),
                ('fechaInicioAtencion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('idMIPRES', models.CharField(blank=True, max_length=15, null=True)),
                ('numAutorizacion', models.CharField(blank=True, max_length=30, null=True)),
                ('numDocumentoIdentificacion', models.CharField(blank=True, max_length=30, null=True)),
                ('vrServicio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valorPagoModerador', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('numFEVPagoModerador', models.CharField(blank=True, max_length=20, null=True)),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
                ('itemFactura', models.IntegerField(blank=True, null=True)),
                ('notasCreditoGlosa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notasCreditoOtras', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notasDebito', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RipsRecienNacido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codPrestador', models.CharField(blank=True, max_length=12, null=True)),
                ('numDocumentoIdentificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fechaNacimiento', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('edadGestacional', models.CharField(blank=True, max_length=2, null=True)),
                ('numConsultasCPrenatal', models.CharField(blank=True, max_length=10, null=True)),
                ('codSexoBiologico', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Indeterminado', 'Indeterminado')], default='A', editable=False, max_length=13)),
                ('peso', models.CharField(blank=True, max_length=10, null=True)),
                ('fechaEgreso', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RipsServicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=4, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsTipoMedicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsTipoOtrosServicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsTipos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsTiposDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsTiposNotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsTiposPagoModerador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('codigoAplicativo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsTipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsTransaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numDocumentoIdObligado', models.CharField(blank=True, max_length=50, null=True)),
                ('numFactura', models.CharField(default='S', editable=False, max_length=20)),
                ('numNota', models.CharField(default='S', editable=False, max_length=20)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RipsUmm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=4, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsUnidadUpr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsUrgenciasObservacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codPrestador', models.CharField(blank=True, max_length=12, null=True)),
                ('fechaInicioAtencion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fechaEgreso', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RipsUsuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDocumentoIdentificacion', models.CharField(blank=True, max_length=9, null=True)),
                ('numDocumentoIdentificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('tipoUsuario', models.CharField(blank=True, max_length=20, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('codSexo', models.CharField(choices=[('H', 'Masculino'), ('M', 'Femenino'), ('I', 'Indeterminado')], default='A', editable=False, max_length=13)),
                ('incapacidad', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='A', editable=False, max_length=2)),
                ('consecutivo', models.CharField(blank=True, max_length=10, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RipsViasAdministracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsViasIngresoSalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RipsZonaTerritorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
