# Generated by Django 2.1.15 on 2025-12-03 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('urgente', models.CharField(blank=True, max_length=1, null=True)),
                ('tipoQx', models.CharField(blank=True, max_length=20, null=True)),
                ('fechaSolicita', models.DateTimeField()),
                ('solicitaHospitalizacion', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('solicitaAyudante', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('solicitaTiempoQx', models.CharField(blank=True, max_length=20, null=True)),
                ('solicitatipoQx', models.CharField(blank=True, max_length=20, null=True)),
                ('solicitaAnestesia', models.CharField(blank=True, max_length=20, null=True)),
                ('solicitaSangre', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('describeSangre', models.CharField(blank=True, max_length=2000, null=True)),
                ('cantidadSangre', models.CharField(blank=True, max_length=10, null=True)),
                ('solicitaCamaUci', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('solicitaMicroscopio', models.CharField(blank=True, max_length=1, null=True)),
                ('solicitaRx', models.CharField(blank=True, max_length=1, null=True)),
                ('solicitaAutoSutura', models.CharField(blank=True, max_length=1, null=True)),
                ('solicitaOsteosintesis', models.CharField(blank=True, max_length=2000, null=True)),
                ('soliictaSoporte', models.CharField(blank=True, max_length=1, null=True)),
                ('solicitaBiopsia', models.CharField(blank=True, max_length=1, null=True)),
                ('solicitaMalla', models.CharField(blank=True, max_length=1, null=True)),
                ('solicitaOtros', models.CharField(blank=True, max_length=1, null=True)),
                ('describeOtros', models.CharField(blank=True, max_length=2000, null=True)),
                ('fechaProg', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('HoraProg', models.CharField(blank=True, max_length=5, null=True)),
                ('ingresoQuirofano', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('horaIngresoQuirofano', models.CharField(blank=True, max_length=8, null=True)),
                ('fechaIniAnestesia', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('HoraIniAnestesia', models.CharField(blank=True, max_length=8, null=True)),
                ('fechaQxInicial', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('horaQxInicial', models.CharField(blank=True, max_length=8, null=True)),
                ('fechaQxFinal', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('horaQxFinal', models.CharField(blank=True, max_length=8, null=True)),
                ('fechaFinAnestesia', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('horaFinAnestesia', models.CharField(blank=True, max_length=8, null=True)),
                ('salidaQuirofano', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('horaSalidaQuirofano', models.CharField(blank=True, max_length=8, null=True)),
                ('ingresoRecuperacion', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('horaIngresoRecuperacion', models.CharField(blank=True, max_length=8, null=True)),
                ('salidaRecuperacion', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('horaSalidaRecuperacion', models.CharField(blank=True, max_length=8, null=True)),
                ('intervencion', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgos', models.CharField(blank=True, max_length=3000, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=5000, null=True)),
                ('descripcionQx', models.CharField(blank=True, max_length=10000, null=True)),
                ('analisis', models.CharField(blank=True, max_length=10000, null=True)),
                ('planx', models.CharField(blank=True, max_length=10000, null=True)),
                ('complicaciones', models.CharField(blank=True, max_length=3000, null=True)),
                ('patologia', models.CharField(blank=True, max_length=500, null=True)),
                ('formaRealiza', models.CharField(blank=True, max_length=15, null=True)),
                ('estadoSalida', models.CharField(blank=True, default='A', max_length=1, null=True)),
                ('vboAdmon', models.CharField(blank=True, max_length=1, null=True)),
                ('hallazgos', models.CharField(blank=True, max_length=5000, null=True)),
                ('osteosintesis', models.CharField(blank=True, max_length=300, null=True)),
                ('auxiliar', models.CharField(blank=True, max_length=200, null=True)),
                ('materialEspecial', models.CharField(blank=True, max_length=300, null=True)),
                ('reprogramada', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('motivoReprogramada', models.CharField(blank=True, max_length=500, null=True)),
                ('tipoCancela', models.CharField(blank=True, max_length=15, null=True)),
                ('motivoCancela', models.CharField(blank=True, max_length=500, null=True)),
                ('tiempoMaxQx', models.CharField(blank=True, max_length=10, null=True)),
                ('observacionesProgramacion', models.CharField(blank=True, max_length=500, null=True)),
                ('fechaPrograma', models.DateTimeField(blank=True, null=True)),
                ('fechaCancela', models.DateTimeField(blank=True, null=True)),
                ('fechaReprograma', models.DateTimeField(blank=True, null=True)),
                ('intensificador', models.CharField(blank=True, max_length=1, null=True)),
                ('tipofractura', models.CharField(blank=True, max_length=40, null=True)),
                ('recomendacionenfermeria', models.CharField(blank=True, max_length=2000, null=True)),
                ('folioEvolucionPreQx', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('folioEvolucionPostQx', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('anulado', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CirugiasMaterialQx',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unitario', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('valorLiquidacion', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('hojaDeGasto', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CirugiasParticipantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CirugiasProcedimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cruento', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], editable=False, max_length=1, null=True)),
                ('incruento', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], editable=False, max_length=1, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosCirugias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosProgramacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosSalas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FinalidadCirugia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GravedadCirugia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HojasDeGastos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='IntervencionCirugias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrganosCirugias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlanificacionCirugia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionCirugias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaProgramacionInicia', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('horaProgramacionInicia', models.CharField(blank=True, max_length=5, null=True)),
                ('fechaProgramacionFin', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('horaProgramacionFin', models.CharField(blank=True, max_length=5, null=True)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RecordAnestesico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('cirugia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.Cirugias')),
            ],
        ),
        migrations.CreateModel(
            name='RegionesOperatorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('organos', models.CharField(blank=True, max_length=250, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposAnestesia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposCirugia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposHeridasOperatorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ViasDeAcceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ZonasCirugia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
    ]
