# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizaciones', '0004_auto_20251203_0815'),
        ('planta', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('contratacion', '0001_initial'),
        ('sitios', '0001_initial'),
        ('facturacion', '0002_auto_20251203_0815'),
        ('tarifarios', '0001_initial'),
        ('clinico', '0002_auto_20251203_0815'),
        ('cirugia', '0002_auto_20251203_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacioncirugias',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria123', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='estadoProgramacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.EstadosProgramacion'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Salas'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm129', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='hojasdegastos',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cirugias17', to='cirugia.Cirugias'),
        ),
        migrations.AddField(
            model_name='hojasdegastos',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='hojasdegastos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cirugias12', to='cirugia.Cirugias'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups104', to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='finalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Final004', to='cirugia.FinalidadCirugia'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='regionOperatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups104', to='cirugia.RegionesOperatorias'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta67', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='viasDeAcceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups104', to='cirugia.ViasDeAcceso'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cirugias13', to='cirugia.Cirugias'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='cirugiaProcedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CiruProc10', to='cirugia.CirugiasProcedimientos'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='finalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Final005', to='cirugia.FinalidadCirugia'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario12', to='clinico.EspecialidadesMedicos'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='tipoHonorarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario12', to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta68', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.Cirugias'),
        ),
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='cirugiaProcedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.CirugiasProcedimientos'),
        ),
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='anestesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.TiposAnestesia'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria54', to='autorizaciones.Autorizaciones'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.Convenios'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria54', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='dxComplicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx555', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='dxPostQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx521', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='dxPreQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx511', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='dxPrinc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx531', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='dxRel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx542', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='estadoCirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.EstadosCirugias'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='estadoProgramacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.EstadosProgramacion'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Historia127', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='impresionDx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx541', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Salas'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm126', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='tiposCirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.TiposCirugia'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='usuarioCancela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Usuario42', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='usuarioPrograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Usuario41', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta39', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='usuarioReprograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Usuario43', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='usuarioSolicita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Usuario40', to='planta.Planta'),
        ),
    ]
