# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('contratacion', '0001_initial'),
        ('sitios', '0001_initial'),
        ('clinico', '0003_auto_20251203_0815'),
        ('facturacion', '0002_auto_20251203_0815'),
        ('tarifarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniostarifashonorarios',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm16', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='conveniostarifashonorarios',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario05', to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='conveniostarifashonorarios',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='conveniostarifashonorarios',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='conveniossuministros',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.Convenios'),
        ),
        migrations.AddField(
            model_name='conveniossuministros',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm17', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='conveniossuministros',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto224', to='facturacion.Conceptos'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.Convenios'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups209', to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm18', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suminis1277', to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario017', to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa037', to='tarifarios.TiposTarifa'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas2177', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Empresas'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm315', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='tarifariosDescripcionHono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TarifariosDescripcionHonor0124', to='tarifarios.TarifariosDescripcionHonorarios'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='tarifariosDescripcionProc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TarifariosDescripcion0121', to='tarifarios.TarifariosDescripcion'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='tarifariosDescripcionSum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TarifariosDescripcion0123', to='tarifarios.TarifariosDescripcion'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AlterUniqueTogether(
            name='conveniostarifashonorarios',
            unique_together={('convenio', 'tipoTarifa', 'tipoHonorario')},
        ),
    ]
