# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSolicitud', models.DateTimeField(blank=True, null=True)),
                ('prioritario', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=5000, null=True)),
                ('numeroAutorizacion', models.CharField(blank=True, max_length=5000, null=True)),
                ('fechaAutorizacion', models.DateTimeField(blank=True, null=True)),
                ('autorizadoPor', models.CharField(blank=True, max_length=80, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('fechaModifica', models.DateTimeField(blank=True, null=True)),
                ('numeroSolicitud', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fechaVigencia', models.DateTimeField(blank=True, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacionesCirugias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hClinica', models.CharField(blank=True, max_length=20, null=True)),
                ('consec', models.IntegerField()),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacionesDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroAutorizacion', models.CharField(blank=True, max_length=5000, null=True)),
                ('cantidadSolicitada', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cantidadAutorizada', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valorSolicitado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valorAutorizado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('autorizaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento88', to='autorizaciones.Autorizaciones')),
            ],
        ),
        migrations.CreateModel(
            name='EstadosAutorizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
    ]
