# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizaciones', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('clinico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='cums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suminist304', to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='estadoAutorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estAut02', to='autorizaciones.EstadosAutorizacion'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='examenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Examen829', to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='historiaMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AutMed01', to='clinico.HistoriaMedicamentos'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='tipoSuministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.TiposSuministro'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='tiposExamen',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
    ]
