# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('autorizaciones', '0002_auto_20251203_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Planta3', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='autorizacionescirugias',
            name='autorizacionesId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento99', to='autorizaciones.Autorizaciones'),
        ),
    ]
