# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('contratacion', '0001_initial'),
        ('sitios', '0001_initial'),
        ('autorizaciones', '0003_auto_20251203_0815'),
        ('facturacion', '0002_auto_20251203_0815'),
        ('clinico', '0002_auto_20251203_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionescirugias',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento9', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='autorizacionescirugias',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica5', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='autorizacionescirugias',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='autorizacionescirugias',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta2', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenios02271', to='contratacion.Convenios'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa765', to='facturacion.Empresas'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='estadoAutorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='autorizaciones.EstadosAutorizacion'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Historia476', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='plantaOrdena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica13', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm03', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta2', to='planta.Planta'),
        ),
    ]
