# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecAdmision', models.IntegerField(default=0)),
                ('tipoAtencion', models.CharField(default='A', editable=False, max_length=20)),
                ('anamnesis', models.CharField(blank=True, max_length=2000, null=True)),
                ('exaFisico', models.CharField(blank=True, max_length=2000, null=True)),
                ('exaDiagnostico', models.CharField(blank=True, max_length=2000, null=True)),
                ('tratamiento', models.CharField(default='A', editable=False, max_length=2000)),
                ('motivoReferencia', models.CharField(blank=True, max_length=2000, null=True)),
                ('otroMotivo', models.CharField(blank=True, max_length=2000, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('fechaPrueba', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
    ]
