# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0002_auto_20251203_0815'),
        ('usuarios', '0001_initial'),
        ('contratacion', '0002_auto_20251203_0815'),
        ('clinico', '0003_auto_20251203_0815'),
        ('referencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.UsuariosContacto'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='convenio1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenio22', to='contratacion.Convenios'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='convenio2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenio23', to='contratacion.Convenios'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cups1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups28', to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cups2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups27', to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cups3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups26', to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cups4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups25', to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cups5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups24', to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cups6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups23', to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria9', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='dxEgreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='dxIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx27', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups22', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='regimerReferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx26', to='clinico.Regimenes'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Servicios'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
    ]
