# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rips', '0001_initial'),
        ('planta', '0001_initial'),
        ('clinico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viasadministracion',
            name='ripsViasAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsViasAdministracion'),
        ),
        migrations.AddField(
            model_name='trasfusiones',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag25', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='trasfusiones',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='tipooxigenacion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='subgrupos',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Grupos'),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag23', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='productosnutricion',
            name='formaFarmaceutica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.FormasFarmaceuticas'),
        ),
        migrations.AddField(
            model_name='productosnutricion',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Presentacion'),
        ),
        migrations.AddField(
            model_name='productosnutricion',
            name='unidades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.UnidadesDeMedida'),
        ),
        migrations.AddField(
            model_name='nivelesregimenes',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Regimenes'),
        ),
    ]
