# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('clinico', '0002_auto_20251203_0815'),
        ('sitios', '0001_initial'),
        ('facturacion', '0002_auto_20251203_0815'),
        ('cirugia', '0003_auto_20251203_0815'),
        ('rips', '0001_initial'),
        ('autorizaciones', '0004_auto_20251203_0815'),
        ('tarifarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Centros'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Ciudades'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Departamentos'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='medicamentosdci',
            name='tipoMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposMedicamento'),
        ),
        migrations.AddField(
            model_name='imhaloterapia',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag27', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='imhaloterapia',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiasignosvitales',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaSig2', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historiasignosvitales',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiarevisionsistemas',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaRev1', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historiarevisionsistemas',
            name='revisionSistemas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.RevisionSistemas'),
        ),
        migrations.AddField(
            model_name='historiarevisionsistemas',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='examenesRasgos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ExamenesRasgos'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='historiaExamenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.HistoriaExamenes'),
        ),
        migrations.AddField(
            model_name='historiaoxigeno',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag29', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historiaoxigeno',
            name='tipoOxigenacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoOxigenacion02', to='clinico.TipoOxigenacion'),
        ),
        migrations.AddField(
            model_name='historiaoxigeno',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiamedicamentos',
            name='cantidadDispensada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsUnidadUpr'),
        ),
        migrations.AddField(
            model_name='historiamedicamentos',
            name='dosisUnidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.UnidadesDeMedidaDosis'),
        ),
        migrations.AddField(
            model_name='historiamedicamentos',
            name='frecuencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.FrecuenciasAplicacion'),
        ),
        migrations.AddField(
            model_name='historiamedicamentos',
            name='historia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag12', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historiamedicamentos',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='historiamedicamentos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiamedicamentos',
            name='viaAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasAdministracion'),
        ),
        migrations.AddField(
            model_name='historialnotasenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaEnfHistoria001', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historialinterconsultas',
            name='diagnosticos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='historialinterconsultas',
            name='especialidadConsulta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.EspecialidadesMedicos'),
        ),
        migrations.AddField(
            model_name='historialinterconsultas',
            name='especialidadConsultada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='espe22', to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='historialinterconsultas',
            name='estadosInterconsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.EstadosInterconsulta'),
        ),
        migrations.AddField(
            model_name='historialinterconsultas',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag11', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historialinterconsultas',
            name='medicoConsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Medicos'),
        ),
        migrations.AddField(
            model_name='historialinterconsultas',
            name='medicoConsultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='med22', to='clinico.Medicos'),
        ),
        migrations.AddField(
            model_name='historialinterconsultas',
            name='tipoInterconsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposInterconsulta'),
        ),
        migrations.AddField(
            model_name='historialincapacidades',
            name='diagnosticosIncapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='historialincapacidades',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag10', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historialincapacidades',
            name='tiposIncapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposIncapacidad'),
        ),
        migrations.AddField(
            model_name='historialenfermedades',
            name='enfermedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfer001', to='clinico.Enfermedades'),
        ),
        migrations.AddField(
            model_name='historialenfermedades',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historia_32', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historialdietas',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dietas001g8', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historialdietas',
            name='tipoDieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoDietas001', to='clinico.TipoDietas'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticoscabezote',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticoscabezote',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticos',
            name='diagnosticos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dxPpal', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticos',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag8', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticos',
            name='tiposDiagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposDiagnostico', to='clinico.TiposDiagnostico'),
        ),
        migrations.AddField(
            model_name='historialcirugias',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cirugia_3221', to='cirugia.Cirugias'),
        ),
        migrations.AddField(
            model_name='historialcirugias',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historia_3223', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historialcirugias',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag9', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='tiposAntecedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposAntecedente'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aut01', to='autorizaciones.Autorizaciones'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='estadoExamenes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.EstadoExamenes'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='medicoInterpretacion1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interpreta01', to='clinico.Medicos'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='medicoInterpretacion2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interpreta02', to='clinico.Medicos'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='medicoInterpretacion3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interpreta03', to='clinico.Medicos'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='medicoReporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medReporte', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='tiposExamen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='usuarioAnula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioAnula1', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='usuarioToma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioToma1', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='usuaroRegistra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistra1', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='causasExterna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.CausasExterna'),
        ),
        migrations.AddField(
            model_name='historia',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria5672', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='historia',
            name='especialidades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='historia',
            name='especialidadesMedicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.EspecialidadesMedicos'),
        ),
        migrations.AddField(
            model_name='historia',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica367', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='historia',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm50', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='historia',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='historia',
            name='tipoEvolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposEvolucion'),
        ),
        migrations.AddField(
            model_name='historia',
            name='tiposFolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposFolio'),
        ),
        migrations.AddField(
            model_name='historia',
            name='usuarioNotaAclaratoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='historia',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lanta345', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='hallazgos',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag13', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='examenesrasgos',
            name='tiposExamen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='examenes',
            name='TiposExamen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='examenes',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Conceptos'),
        ),
        migrations.AddField(
            model_name='examenes',
            name='grupoQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.GruposQx'),
        ),
        migrations.AddField(
            model_name='examenes',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario76091', to='tarifarios.TiposHonorarios'),
        ),
        migrations.AddField(
            model_name='examenes',
            name='tipoRadiologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposRadiologia'),
        ),
        migrations.AddField(
            model_name='especialidadesmedicos',
            name='especialidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especialidadesMedicos1', to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='especialidadesmedicos',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='especialidadesmedicos',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica301', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='especialidadesmedicos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='especialidades',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='especialidades',
            name='examenCita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuposCita', to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='antibiotico',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag28', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='antibiotico',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sumins03', to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='antibiotico',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AlterUniqueTogether(
            name='medicos',
            unique_together={('planta',)},
        ),
        migrations.AddIndex(
            model_name='historiarevisionsistemas',
            index=models.Index(fields=['historia'], name='clinico_his_histori_5127ef_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaresultados',
            index=models.Index(fields=['historiaExamenes'], name='clinico_his_histori_4fd783_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaoxigeno',
            index=models.Index(fields=['historia'], name='clinico_his_histori_9ec0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='historiamedicamentos',
            index=models.Index(fields=['historia'], name='clinico_his_histori_5d8f52_idx'),
        ),
        migrations.AddIndex(
            model_name='historialnotasenfermeria',
            index=models.Index(fields=['historia'], name='clinico_his_histori_5c1023_idx'),
        ),
        migrations.AddIndex(
            model_name='historialinterconsultas',
            index=models.Index(fields=['historia'], name='clinico_his_histori_4e9271_idx'),
        ),
        migrations.AddIndex(
            model_name='historialincapacidades',
            index=models.Index(fields=['historia'], name='clinico_his_histori_6a14c3_idx'),
        ),
        migrations.AddIndex(
            model_name='historialenfermedades',
            index=models.Index(fields=['historia'], name='clinico_his_histori_d4219e_idx'),
        ),
        migrations.AddIndex(
            model_name='historialdietas',
            index=models.Index(fields=['historia'], name='clinico_his_histori_01b799_idx'),
        ),
        migrations.AddIndex(
            model_name='historialdiagnosticos',
            index=models.Index(fields=['historia'], name='clinico_his_histori_22d2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcirugias',
            index=models.Index(fields=['historia'], name='clinico_his_histori_5721fb_idx'),
        ),
        migrations.AddIndex(
            model_name='historialantecedentes',
            index=models.Index(fields=['historia'], name='clinico_his_histori_961a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaexamenes',
            index=models.Index(fields=['historia'], name='clinico_his_histori_f4c7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='historia',
            index=models.Index(fields=['tipoDoc', 'documento', 'folio'], name='clinico_his_tipoDoc_68a6a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historia',
            unique_together={('tipoDoc', 'documento', 'consecAdmision', 'folio')},
        ),
        migrations.AddIndex(
            model_name='examenes',
            index=models.Index(fields=['nombre'], name='examenesNombreIdx'),
        ),
        migrations.AlterUniqueTogether(
            name='especialidadesmedicos',
            unique_together={('sedesClinica', 'planta', 'especialidades')},
        ),
    ]
