# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingresoPaciente', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmaciaDespachos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmaciaDespachosDispensa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dosisCantidad', models.DecimalField(decimal_places=3, max_digits=20)),
                ('cantidadOrdenada', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cantidadDevuelta', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('netoCantidad', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmaciaDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecutivoMedicamento', models.IntegerField(blank=True, null=True)),
                ('dosisCantidad', models.DecimalField(decimal_places=3, max_digits=20)),
                ('cantidadOrdenada', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmaciaDevolucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmaciaDevolucionDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadDevuelta', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cantidadDevueltaRecibida', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmaciaEstados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='A', max_length=50)),
                ('estadoReg', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1, null=True)),
            ],
        ),
    ]
