# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacia', '0001_initial'),
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmaciaestados',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3459', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='farmaciadevoluciondetalle',
            name='farmaciaDespachosDispensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDespachos21201', to='farmacia.FarmaciaDespachosDispensa'),
        ),
        migrations.AddField(
            model_name='farmaciadevoluciondetalle',
            name='farmaciaDevolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDevolucion01', to='farmacia.FarmaciaDevolucion'),
        ),
        migrations.AddField(
            model_name='farmaciadevoluciondetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaFarmaciaDevDet3453', to='planta.Planta'),
        ),
    ]
