# Generated by Django 2.1.15 on 2025-12-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('farmacia', '0002_auto_20251203_0815'),
        ('sitios', '0001_initial'),
        ('facturacion', '0003_auto_20251203_0815'),
        ('enfermeria', '0003_auto_20251203_0815'),
        ('clinico', '0003_auto_20251203_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmaciadevolucion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica39022', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='farmaciadevolucion',
            name='serviciosAdministrativosDevuelve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servDevuelve331', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='farmaciadevolucion',
            name='serviciosAdministrativosRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servRecibe3231', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='farmaciadevolucion',
            name='usuarioDevuelve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaDevuelve453', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='farmaciadevolucion',
            name='usuarioRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaRecibe453', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='farmaciadevolucion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaFarmaciaDev3453', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='dosisUnidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.UnidadesDeMedidaDosis'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Farmacia01', to='farmacia.Farmacia'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='historiaMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmFarm01', to='clinico.HistoriaMedicamentos'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3451', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='viaAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasAdministracion'),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDespachos01', to='farmacia.FarmaciaDespachos'),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='dosisUnidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.UnidadesDeMedidaDosis'),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='farmaciaDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDetalle01', to='farmacia.FarmaciaDetalle'),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Suministros'),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaFarmacia2253', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='viaAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ViasAdministracion'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaDespacho02', to='farmacia.Farmacia'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='serviciosAdministrativosEntrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmFarm02', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='serviciosAdministrativosRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmFarm03', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='usuarioEntrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3472', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='usuarioRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3473', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3452', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Farmaciaestados01', to='farmacia.FarmaciaEstados'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaFarmacia01', to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica390', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmFarm01', to='sitios.ServiciosAdministrativos'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='tipoMovimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoEnfermeria05', to='enfermeria.EnfermeriaTipoMovimiento'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='tipoOrigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoEnfermeria04', to='enfermeria.EnfermeriaTipoOrigen'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3450', to='planta.Planta'),
        ),
    ]
